### ISSUE TITLE
The deployed website is crashing from today

### ISSUE THREAD

**Issue by srid** [DioxusLabs/docsite#139]
The docsite was working until today.

In the browser console (macOS; Brave; guard disabled), I see:

```
docsite.js:725 ERROR /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-web-0.4.0/src/lib.rs:219 Rehydration failed NodeNotFound. Rebuild DOM into element from scratch
inline0.js:255 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'listening')
    at run (inline0.js:255:330)
    at dioxus_interpreter_js::sledgehammer_bindings::Channel::flush::h3dd42f069636a006 (docsite_bg.wasm:0xaa7cd)
    at dioxus_web::dom::WebsysDom::apply_edits::h8dea4df7adec0978 (docsite_bg.wasm:0x7f70a)
    at dioxus_web::run_with_props::{{closure}}::hd8fbd61113cac6f4 (docsite_bg.wasm:0x7ed66)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4af736430e73b26a (docsite_bg.wasm:0xe5a45)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9e889b7261c861ea (docsite_bg.wasm:0x175211)
    at __wbg_adapter_63 (docsite.js:332:10)
    at real (docsite.js:236:20)

```

<img width="1072" alt="image" src="https://github.com/DioxusLabs/docsite/assets/3998/a3e2b95c-5015-4e91-b89e-63f7a45ac150">

**Comment by ealmloff** [comment]
What page are you on? The docs and homepage work correctly on my MacOs, brave, guard disabled browser.

If you are interested in debugging this issue, turning the tracing level to log [here](https://github.com/DioxusLabs/docsite/blob/master/src/main.rs#L13) will show what node the page failed to hydrate on

**Comment by srid** [comment]
I see it on https://dioxuslabs.com/learn/0.4/reference/dynamic_rendering in particular, but not many of the other pages

**Comment by hanool** [comment]
Are you using `Dark-Reader` or similar browser extensions?
I had the same error message on browser console.
Disabled `Dark-Reader` after I saw this issue #91 and now it works fine.

**Comment by srid** [comment]
It is still reproducible without browser extensions.

**Comment by ealmloff** [comment]
Reopening this until the docsite bumps to 0.5

**Comment by dromse** [comment]
+1 I have this error with DarkReader too
