### ISSUE TITLE
JS errors on `Dynamic Rendering` page 

### ISSUE THREAD

**Issue by chungwong** [DioxusLabs/docsite#197]
Visiting **_directly_** https://dioxuslabs.com/learn/0.4/reference/dynamic_rendering on different browsers triggered different errors.

1. On Chrome Version 120.0.6099.129 (Official Build) (64-bit)
```
inline0.js:261 Uncaught TypeError: Cannot read properties of undefined (reading 'listening')
    at run (inline0.js:261:330)
    at dioxus_interpreter_js::sledgehammer_bindings::Channel::flush::hc2ba28660d22c4fa (docsite_bg.wasm:0xb7d35)
    at dioxus_web::dom::WebsysDom::apply_edits::h0f7eb15f682a8433 (docsite_bg.wasm:0x89624)
    at dioxus_web::run_with_props::{{closure}}::h96160061241bfb9a (docsite_bg.wasm:0x74e2a)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::hc3db65e775e1ad98 (docsite_bg.wasm:0xf9f71)
    at wasm_bindgen::convert::closures::invoke1_mut::h7a41a7622926d308 (docsite_bg.wasm:0x17fb05)
    at __wbg_adapter_63 (docsite.js:331:10)
    at real (docsite.js:236:20)
```

2. On Firefox 115.6.0esr (64-bit)
```
Uncaught TypeError: root is undefined
    run https://dioxuslabs.com/assets/dioxus/snippets/dioxus-interpreter-js-85a0a2f8acce2e86/inline0.js:261
    __wbg_adapter_63 https://dioxuslabs.com/assets/dioxus/docsite.js:331
    real https://dioxuslabs.com/assets/dioxus/docsite.js:236
    __wbg_queueMicrotask_4d890031a6a5a50c https://dioxuslabs.com/assets/dioxus/docsite.js:590
    logError https://dioxuslabs.com/assets/dioxus/docsite.js:253
    __wbg_queueMicrotask_4d890031a6a5a50c https://dioxuslabs.com/assets/dioxus/docsite.js:589
    __wbg_adapter_63 https://dioxuslabs.com/assets/dioxus/docsite.js:331
    real https://dioxuslabs.com/assets/dioxus/docsite.js:236
    promise callback*__wbg_get_imports/imports.wbg.__wbg_then_8371cc12cfedc5a2/< https://dioxuslabs.com/assets/dioxus/docsite.js:1448
    logError https://dioxuslabs.com/assets/dioxus/docsite.js:253
    __wbg_then_8371cc12cfedc5a2 https://dioxuslabs.com/assets/dioxus/docsite.js:1447
    __wbg_adapter_63 https://dioxuslabs.com/assets/dioxus/docsite.js:331
    real https://dioxuslabs.com/assets/dioxus/docsite.js:236
    __wbg_queueMicrotask_4d890031a6a5a50c https://dioxuslabs.com/assets/dioxus/docsite.js:590
    logError https://dioxuslabs.com/assets/dioxus/docsite.js:253
    __wbg_queueMicrotask_4d890031a6a5a50c https://dioxuslabs.com/assets/dioxus/docsite.js:589
    __wbg_finalize_init https://dioxuslabs.com/assets/dioxus/docsite.js:1569
    __wbg_init https://dioxuslabs.com/assets/dioxus/docsite.js:1603
    async* https://dioxuslabs.com/learn/0.4/reference/dynamic_rendering/:275
[inline0.js:261:325](https://dioxuslabs.com/assets/dioxus/snippets/dioxus-interpreter-js-85a0a2f8acce2e86/inline0.js)
```

Now the links at the left hand side panel didn't work, it could be related to the above errors.

**Comment by ealmloff** [comment]
I think https://github.com/DioxusLabs/dioxus/pull/1732 fixes this issue, but the docsite relies on the 0.4 version of dioxus so that we can check that doc examples compile on 0.4, not the git version of dioxus

**Comment by chungwong** [comment]
Closing this as it is duplicated.
Refs
https://github.com/DioxusLabs/docsite/issues/91
https://github.com/DioxusLabs/docsite/issues/139
